eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck: true
  instance:
     preferIpAddress: true
     
spring:
  application:
    name: user-provider
    
endpoints:
  env:
    enabled: true