server:
  port: 8761

spring:
   application:
    name: discover-server
    
eureka:
  instance:
    hostname: localhost
  dashboard:
    enabled: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/